import { Link } from "react-router-dom";
import { ArrowRight, Mail, Phone, MapPin } from "lucide-react";

import PageHero from "../components/PageHero";
import Button from "../components/Button";
import { clinic } from "../data/site";

const LAST_UPDATED = "April 2026";

export default function Privacy() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        description={`Last updated: ${LAST_UPDATED}`}
      />

      <section className="section">
        <div className="container-px mx-auto max-w-3xl">
          <article className="space-y-12 text-[15px] leading-relaxed text-ink-700">
            <Intro />
            <Section title="Interpretation and Definitions">
              <H3>Interpretation</H3>
              <P>
                The words of which the initial letter is capitalized have
                meanings defined under the following conditions. The following
                definitions shall have the same meaning regardless of whether
                they appear in singular or in plural.
              </P>

              <H3>Definitions</H3>
              <P>For the purposes of this Privacy Policy:</P>
              <DefList>
                <DefItem term="Company">
                  (referred to as either "the Company", "We", "Us" or "Our" in
                  this Agreement) refers to {clinic.shortName} {clinic.city},{" "}
                  {clinic.address}.
                </DefItem>
                <DefItem term="Website">
                  refers to {clinic.shortName} {clinic.city}.
                </DefItem>
                <DefItem term="Service">refers to the Website.</DefItem>
                <DefItem term="Personal Data">
                  is any information that relates to an identified or
                  identifiable individual.
                </DefItem>
                <DefItem term="Usage Data">
                  refers to data collected automatically, either generated by
                  the use of the Service or from the Service infrastructure
                  itself.
                </DefItem>
                <DefItem term="You">
                  means the individual accessing or using the Service.
                </DefItem>
              </DefList>
            </Section>

            <Section title="Collecting and Using Your Personal Data">
              <H3>Types of Data Collected</H3>

              <H4>Personal Data</H4>
              <P>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. Personally identifiable information
                may include, but is not limited to:
              </P>
              <UL>
                <li>Name</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Appointment date and time preferences</li>
                <li>Treatment preferences</li>
              </UL>

              <H4>Usage Data</H4>
              <P>
                Usage Data is collected automatically when using the Service.
                Usage Data may include information such as Your Device's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that You visit, the
                time and date of Your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </P>

              <H3>Tracking Technologies and Cookies</H3>
              <P>
                We use Cookies and similar tracking technologies to track the
                activity on Our Service and store certain information.
                Technologies used may include Google Tag Manager, analytics
                cookies, and functional cookies to enhance user experience.
              </P>

              <H3>Use of Your Personal Data</H3>
              <P>The Company may use Personal Data for the following purposes:</P>
              <UL>
                <li>To provide and maintain our Service</li>
                <li>To manage Your appointments and bookings</li>
                <li>
                  To contact You regarding your appointments, treatments, or
                  inquiries
                </li>
                <li>
                  To provide You with news, special offers and general
                  information about our services
                </li>
                <li>To manage Your requests</li>
                <li>For business transfers or other legal requirements</li>
              </UL>

              <H3>Retention of Your Personal Data</H3>
              <P>
                The Company will retain Your Personal Data only for as long as
                is necessary for the purposes set out in this Privacy Policy.
                We will retain and use Your Personal Data to the extent
                necessary to comply with our legal obligations, resolve
                disputes, and enforce our agreements.
              </P>

              <H3>Transfer of Your Personal Data</H3>
              <P>
                Your information, including Personal Data, is processed at the
                Company's operating offices and in any other places where the
                parties involved in the processing are located. Your consent to
                this Privacy Policy followed by Your submission of such
                information represents Your agreement to that transfer.
              </P>

              <H3>Delete Your Personal Data</H3>
              <P>
                You have the right to delete or request that We assist in
                deleting the Personal Data that We have collected about You.
                You may contact us to request access to, correct, or delete any
                personal information that you have provided to us.
              </P>
            </Section>

            <Section title="Disclosure of Your Personal Data">
              <H3>Business Transactions</H3>
              <P>
                If the Company is involved in a merger, acquisition or asset
                sale, Your Personal Data may be transferred. We will provide
                notice before Your Personal Data is transferred and becomes
                subject to a different Privacy Policy.
              </P>

              <H3>Law Enforcement</H3>
              <P>
                Under certain circumstances, the Company may be required to
                disclose Your Personal Data if required to do so by law or in
                response to valid requests by public authorities.
              </P>

              <H3>Other Legal Requirements</H3>
              <P>
                The Company may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
              </P>
              <UL>
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>
                  Prevent or investigate possible wrongdoing in connection with
                  the Service
                </li>
                <li>
                  Protect the personal safety of Users of the Service or the
                  public
                </li>
                <li>Protect against legal liability</li>
              </UL>
            </Section>

            <Section title="Security of Your Personal Data">
              <P>
                The security of Your Personal Data is important to Us, but
                remember that no method of transmission over the Internet, or
                method of electronic storage is 100% secure. While We strive to
                use commercially acceptable means to protect Your Personal
                Data, We cannot guarantee its absolute security.
              </P>
            </Section>

            <Section title="Children's Privacy">
              <P>
                Our Service does not address anyone under the age of 13. We do
                not knowingly collect personally identifiable information from
                anyone under the age of 13. If You are a parent or guardian and
                You are aware that Your child has provided Us with Personal
                Data, please contact Us.
              </P>
            </Section>

            <Section title="Links to Other Websites">
              <P>
                Our Service may contain links to other websites that are not
                operated by Us. We strongly advise You to review the Privacy
                Policy of every site You visit. We have no control over and
                assume no responsibility for the content, privacy policies or
                practices of any third party sites or services.
              </P>
            </Section>

            <Section title="Changes to this Privacy Policy">
              <P>
                We may update Our Privacy Policy from time to time. We will
                notify You of any changes by posting the new Privacy Policy on
                this page and updating the "Last updated" date at the top of
                this Privacy Policy.
              </P>
            </Section>

            <ContactCard />
          </article>

          <div className="mt-14 flex flex-wrap items-center justify-center gap-3">
            <Button to="/" variant="secondary">
              Return Home
            </Button>
            <Link
              to="/contact"
              className="btn-base text-ink-700 hover:text-brand-600"
            >
              Contact us
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}

/* ----------------------------- helpers ----------------------------- */

function Intro() {
  return (
    <div className="rounded-3xl bg-ink-50/60 p-6 ring-1 ring-ink-100 sm:p-8">
      <p className="text-[15px] leading-relaxed text-ink-700">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law
        protects You.
      </p>
      <p className="mt-4 text-[15px] leading-relaxed text-ink-700">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section>
      <h2 className="text-2xl font-semibold tracking-tight text-ink-900 sm:text-3xl">
        {title}
      </h2>
      <div className="mt-5 space-y-4">{children}</div>
    </section>
  );
}

function H3({ children }) {
  return (
    <h3 className="mt-6 text-lg font-semibold tracking-tight text-ink-900">
      {children}
    </h3>
  );
}

function H4({ children }) {
  return (
    <h4 className="mt-4 text-[15px] font-semibold tracking-tight text-ink-800">
      {children}
    </h4>
  );
}

function P({ children }) {
  return <p className="text-[15px] leading-relaxed text-ink-700">{children}</p>;
}

function UL({ children }) {
  return (
    <ul className="ml-1 space-y-2 text-[15px] leading-relaxed text-ink-700">
      {Array.isArray(children)
        ? children.map((c, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="mt-2 h-1.5 w-1.5 flex-none rounded-full bg-brand-500" />
              <span>{c.props ? c.props.children : c}</span>
            </li>
          ))
        : children}
    </ul>
  );
}

function DefList({ children }) {
  return <ul className="space-y-3">{children}</ul>;
}

function DefItem({ term, children }) {
  return (
    <li className="flex flex-col gap-1 rounded-2xl bg-white p-4 ring-1 ring-ink-100 sm:flex-row sm:gap-3">
      <span className="flex-none text-sm font-semibold text-brand-700 sm:w-32">
        {term}
      </span>
      <span className="text-[14px] leading-relaxed text-ink-700">
        {children}
      </span>
    </li>
  );
}

function ContactCard() {
  return (
    <section>
      <h2 className="text-2xl font-semibold tracking-tight text-ink-900 sm:text-3xl">
        Contact Us
      </h2>
      <p className="mt-5 text-[15px] leading-relaxed text-ink-700">
        If you have any questions about this Privacy Policy, You can contact
        us:
      </p>

      <div className="mt-5 grid gap-3 sm:grid-cols-3">
        <ContactItem
          icon={Mail}
          label="Email"
          value={
            <a
              href={`mailto:${clinic.email}`}
              className="hover:text-brand-600"
            >
              {clinic.email}
            </a>
          }
        />
        <ContactItem
          icon={Phone}
          label="Phone"
          value={
            <a
              href={`tel:${clinic.phone.replace(/\s/g, "")}`}
              className="hover:text-brand-600"
            >
              {clinic.phone}
            </a>
          }
        />
        <ContactItem
          icon={MapPin}
          label="In person"
          value={
            <Link to="/contact" className="hover:text-brand-600">
              Visit the {clinic.city} clinic
            </Link>
          }
        />
      </div>
    </section>
  );
}

function ContactItem({ icon: Icon, label, value }) {
  return (
    <div className="rounded-2xl bg-white p-4 ring-1 ring-ink-100">
      <div className="flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-brand-50 text-brand-600 ring-1 ring-brand-100">
          <Icon className="h-4 w-4" />
        </span>
        <div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-ink-500">
          {label}
        </div>
      </div>
      <div className="mt-3 text-sm font-medium text-ink-800">{value}</div>
    </div>
  );
}
